# Generated by Django 5.2.3 on 2025-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.TextField(blank=True, verbose_name='Плотность'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(blank=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.TextField(blank=True, verbose_name='SKU'),
        ),
    ]
